# Cloud-config
# Create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

write_files:
- path: /etc/environment
  append: true
  content: |
    JAVA_HOME_8_X64="/usr/lib/jvm/java-8-openjdk-amd64/bin/java"
    JAVA_HOME_11_X64="/usr/lib/jvm/java-11-openjdk-amd64/bin/java"
    JAVA_HOME_17_X64="/usr/lib/jvm/java-17-openjdk-amd64/bin/java"
# runcmd:

bootcmd:
  - mkdir -p /etc/systemd/system/walinuxagent.service.d
  - echo "[Unit]\nAfter=cloud-final.service" > /etc/systemd/system/walinuxagent.service.d/override.conf
  - sed "s/After=multi-user.target//g" /lib/systemd/system/cloud-final.service > /etc/systemd/system/cloud-final.service
  - systemctl daemon-reload